from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Create a router and register our viewsets with it
router = DefaultRouter()
router.register(r'categories', views.ServiceCategoryViewSet, basename='servicecategory')
router.register(r'images', views.ServiceImageViewSet, basename='serviceimage')
router.register(r'services', views.ServiceViewSet, basename='service')
router.register(r'availability', views.ServiceAvailabilityViewSet, basename='serviceavailability')
router.register(r'faqs', views.ServiceFAQViewSet, basename='servicefaq')
router.register(r'views', views.ServiceViewViewSet, basename='serviceview')

app_name = 'services'

urlpatterns = [
    # Include the router URLs
    path('', include(router.urls)),
    
    # Additional custom URLs (if needed)
    # These would be for any non-viewset based views
    path('service-types/', views.service_type_choices, name='service-type-choices'),
    # Service category specific URLs
    path('categories/<int:pk>/services/', 
         views.ServiceCategoryViewSet.as_view({'get': 'services'}), 
         name='category-services'),
    
    # Service specific URLs
    path('services/my-services/', 
         views.ServiceViewSet.as_view({'get': 'my_services'}), 
         name='my-services'),
    
    path('services/featured/', 
         views.ServiceViewSet.as_view({'get': 'featured'}), 
         name='featured-services'),
    
    path('services/popular/', 
         views.ServiceViewSet.as_view({'get': 'popular'}), 
         name='popular-services'),
    
    path('services/search/', 
         views.ServiceViewSet.as_view({'get': 'search'}), 
         name='search-services'),
    
    path('services/stats/', 
         views.ServiceViewSet.as_view({'get': 'stats'}), 
         name='service-stats'),
    
    path('services/<int:pk>/update-status/', 
         views.ServiceViewSet.as_view({'post': 'update_status'}), 
         name='service-update-status'),
    
    path('services/<int:pk>/add-to-favorites/', 
         views.ServiceViewSet.as_view({'post': 'add_to_favorites'}), 
         name='service-add-to-favorites'),
    
    path('services/<int:pk>/remove-from-favorites/', 
         views.ServiceViewSet.as_view({'post': 'remove_from_favorites'}), 
         name='service-remove-from-favorites'),
    
    # Service view analytics URLs
    path('views/analytics/', 
         views.ServiceViewViewSet.as_view({'get': 'analytics'}), 
         name='service-view-analytics'),
]

# URL patterns that will be generated by the router:
# GET    /categories/                     - List all categories
# GET    /categories/{id}/               - Retrieve a specific category
# GET    /categories/{id}/services/      - List services in a category
# 
# GET    /images/                        - List all service images
# GET    /images/{id}/                   - Retrieve a specific image
# 
# GET    /services/                      - List all services
# POST   /services/                      - Create a new service
# GET    /services/{id}/                 - Retrieve a specific service
# PUT    /services/{id}/                 - Update a service
# PATCH  /services/{id}/                 - Partially update a service
# DELETE /services/{id}/                 - Delete a service
# GET    /services/my-services/          - Get current provider's services
# GET    /services/featured/             - Get featured services
# GET    /services/popular/              - Get popular services
# GET    /services/search/               - Advanced search
# GET    /services/stats/                - Service statistics (Admin only)
# POST   /services/{id}/update-status/   - Update service status (Admin only)
# POST   /services/{id}/add-to-favorites/ - Add to favorites
# POST   /services/{id}/remove-from-favorites/ - Remove from favorites
# 
# GET    /availability/                  - List service availability
# POST   /availability/                  - Create availability
# GET    /availability/{id}/             - Retrieve availability
# PUT    /availability/{id}/             - Update availability
# PATCH  /availability/{id}/             - Partially update availability
# DELETE /availability/{id}/             - Delete availability
# 
# GET    /faqs/                          - List service FAQs
# POST   /faqs/                          - Create FAQ
# GET    /faqs/{id}/                     - Retrieve FAQ
# PUT    /faqs/{id}/                     - Update FAQ
# PATCH  /faqs/{id}/                     - Partially update FAQ
# DELETE /faqs/{id}/                     - Delete FAQ
# 
# GET    /views/                         - List service views (Admin only)
# GET    /views/{id}/                    - Retrieve service view (Admin only)
# GET    /views/analytics/               - View analytics (Admin only)