# Generated by Django 5.2.5 on 2026-02-03 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='flight_direct_via',
            field=models.CharField(blank=True, choices=[('direct', 'Direct'), ('via', 'Via')], max_length=10, verbose_name='Flight Type'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('bus', 'Bus'), ('cab', 'Cab'), ('other', 'Other')], max_length=50, verbose_name='Transport Type'),
        ),
    ]
