# Generated by Django 5.2.4 on 2025-08-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_drop_location_service_flight_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='flight_from',
            field=models.CharField(blank=True, help_text='Origin airport/city for flight', max_length=100, null=True, verbose_name='Flight From'),
        ),
        migrations.AlterField(
            model_name='service',
            name='flight_to',
            field=models.CharField(blank=True, help_text='Destination airport/city for flight', max_length=100, null=True, verbose_name='Flight To'),
        ),
    ]
