# Generated by Django 5.2.4 on 2025-08-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_service_flight_from_alter_service_flight_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='hotel_amenities',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
