# Generated by Django 5.2.4 on 2025-08-21 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_service_hotel_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='hotel_amenities',
        ),
    ]
