# Generated by Django 5.2.5 on 2026-02-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='package',
            name='package_category',
            field=models.CharField(choices=[('deluxe', 'Deluxe'), ('semi-deluxe', 'Semi-Deluxe'), ('economy', 'Economy'), ('budget', 'Budget')], default='economy', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='short_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='package',
            name='booking_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('hajj', 'Hajj'), ('umrah', 'Umrah'), ('both', 'Hajj & Umrah'), ('zyarat', 'Zyarat'), ('ramzan', 'Ramzan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
