# Generated by Django 5.2.4 on 2025-08-04 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_package_featured_image'),
        ('services', '0004_alter_service_verified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_packages', to='services.serviceimage'),
        ),
    ]
