# Generated by Django 5.2.5 on 2026-02-20 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_features_package_package_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='package_videos/'),
        ),
        migrations.CreateModel(
            name='ProviderPackageImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='provider_package_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_images', to='packages.package')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
