# Generated by Django 5.2.5 on 2026-09-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_package_video_providerpackageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='departure_city',
            field=models.CharField(blank=True, help_text='City of departure', max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='group_departure_dates',
            field=models.JSONField(blank=True, default=list, help_text='List of group departure dates'),
        ),
    ]
