# Generated by Django 5.2.4 on 2025-08-05 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('packages', '0003_alter_package_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='authentication.serviceproviderprofile'),
        ),
    ]
