# Generated by Django 5.2.5 on 2026-09-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_package_departure_city_package_group_departure_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_category',
            field=models.CharField(choices=[('luxury', 'Luxury'), ('deluxe', 'Deluxe'), ('semi-deluxe', 'Semi-Deluxe'), ('economy', 'Economy'), ('budget', 'Budget')], default='economy', max_length=20),
        ),
    ]
