# Generated by Django 5.2.4 on 2025-08-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_package_city_package_country_package_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='booking_deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration_days',
            field=models.PositiveIntegerField(),
        ),
    ]
