# Generated by Django 5.2.4 on 2025-08-07 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('packages', '0006_alter_package_booking_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='authentication.serviceproviderprofile'),
        ),
    ]
