# Generated by Django 5.2.5 on 2026-02-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPincode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pincode', models.CharField(db_index=True, max_length=10)),
                ('area_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
            ],
            options={
                'verbose_name': 'Master Pincode',
                'verbose_name_plural': 'Master Pincodes',
                'ordering': ['pincode', 'area_name'],
                'unique_together': {('pincode', 'area_name')},
            },
        ),
    ]
