# Generated by Django 5.2.5 on 2025-09-01 07:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_initial'),
        ('packages', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('package', 'Package'), ('service', 'Service'), ('custom', 'Custom')], default='package', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('number_of_people', models.PositiveIntegerField(default=1)),
                ('budget_range', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_city', models.CharField(blank=True, max_length=100, null=True)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('selected_services', models.JSONField(default=dict)),
                ('is_distributed', models.BooleanField(default=False)),
                ('distribution_date', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='web', max_length=50)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('service_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.serviceproviderprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadInteraction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('meeting', 'Meeting'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('interaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('outcome_notes', models.TextField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='leads.lead')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='authentication.serviceproviderprofile')),
            ],
            options={
                'db_table': 'lead_interactions',
                'ordering': ['-interaction_date'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('is_private', models.BooleanField(default=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='authentication.serviceproviderprofile')),
            ],
            options={
                'db_table': 'lead_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadDistribution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('viewed', 'Viewed'), ('responded', 'Responded'), ('ignored', 'Ignored')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='leads.lead')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_distributions', to='authentication.serviceproviderprofile')),
            ],
            options={
                'db_table': 'lead_distributions',
                'ordering': ['-sent_at'],
                'unique_together': {('lead', 'provider')},
            },
        ),
    ]
