# Generated by Django 5.2.4 on 2025-07-18 21:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lead_type', models.CharField(choices=[('package', 'Package'), ('service', 'Service'), ('custom', 'Custom')], default='package', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('number_of_people', models.PositiveIntegerField(default=1)),
                ('budget_range', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_city', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_hotel_category', models.CharField(blank=True, max_length=50, null=True)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('custom_message', models.TextField(blank=True, null=True)),
                ('selected_services', models.JSONField(default=dict, help_text='JSON field to store selected services for custom packages')),
                ('is_distributed', models.BooleanField(default=False)),
                ('distribution_date', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='web', help_text='Source of lead: web, app, etc.', max_length=50)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='packages.package')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadDistribution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('viewed', 'Viewed'), ('responded', 'Responded'), ('ignored', 'Ignored')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('app_notification_sent', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='leads.lead')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lead_distributions',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadInteraction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('meeting', 'Meeting'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('interaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True, null=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('outcome_notes', models.TextField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='leads.lead')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lead_interactions',
                'ordering': ['-interaction_date'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('is_private', models.BooleanField(default=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lead_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['user', 'status'], name='leads_user_id_57eab3_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['package', 'status'], name='leads_package_7f3c00_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['service', 'status'], name='leads_service_0d1945_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['preferred_date'], name='leads_preferr_43c140_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_distributed'], name='leads_is_dist_336b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='leads_created_e6e479_idx'),
        ),
        migrations.AddIndex(
            model_name='leaddistribution',
            index=models.Index(fields=['lead', 'provider'], name='lead_distri_lead_id_80d688_idx'),
        ),
        migrations.AddIndex(
            model_name='leaddistribution',
            index=models.Index(fields=['provider', 'status'], name='lead_distri_provide_1419cd_idx'),
        ),
        migrations.AddIndex(
            model_name='leaddistribution',
            index=models.Index(fields=['sent_at'], name='lead_distri_sent_at_bb39d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaddistribution',
            unique_together={('lead', 'provider')},
        ),
        migrations.AddIndex(
            model_name='leadinteraction',
            index=models.Index(fields=['lead', 'provider'], name='lead_intera_lead_id_b9024a_idx'),
        ),
        migrations.AddIndex(
            model_name='leadinteraction',
            index=models.Index(fields=['interaction_date'], name='lead_intera_interac_395f50_idx'),
        ),
        migrations.AddIndex(
            model_name='leadnote',
            index=models.Index(fields=['lead', 'provider'], name='lead_notes_lead_id_421b7c_idx'),
        ),
    ]
