# Generated by Django 5.2.4 on 2025-08-06 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaddistribution',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_leads', to='authentication.serviceproviderprofile'),
        ),
        migrations.AlterField(
            model_name='leadinteraction',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_interactions', to='authentication.serviceproviderprofile'),
        ),
        migrations.AlterField(
            model_name='leadnote',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_notes', to='authentication.serviceproviderprofile'),
        ),
    ]
