# Generated by Django 5.2.5 on 2025-12-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='selected_services',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
