# Generated by Django 5.2.4 on 2025-08-06 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('leads', '0002_alter_leaddistribution_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_created', to='authentication.serviceproviderprofile'),
        ),
    ]
