# Generated by Django 5.2.5 on 2026-05-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_selected_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('package', 'Package'), ('service', 'Service'), ('custom', 'Custom'), ('contact_view', 'Contact View')], default='package', max_length=20),
        ),
    ]
