# Generated by Django 5.2.4 on 2025-08-06 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('leads', '0003_lead_service_provider'),
        ('packages', '0004_alter_package_provider'),
        ('services', '0005_alter_service_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='leads_status_94f025_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['expires_at'], name='leads_expires_9de04f_idx'),
        ),
        migrations.AddIndex(
            model_name='leaddistribution',
            index=models.Index(fields=['status'], name='lead_distri_status_fc39a6_idx'),
        ),
        migrations.AddIndex(
            model_name='leadinteraction',
            index=models.Index(fields=['interaction_type'], name='lead_intera_interac_40e2bc_idx'),
        ),
        migrations.AddIndex(
            model_name='leadinteraction',
            index=models.Index(fields=['is_successful'], name='lead_intera_is_succ_835f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='leadnote',
            index=models.Index(fields=['is_private'], name='lead_notes_is_priv_885890_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('number_of_people__gt', 0)), name='positive_number_of_people'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('priority__gte', 0)), name='non_negative_priority'),
        ),
        migrations.AddConstraint(
            model_name='leaddistribution',
            constraint=models.CheckConstraint(condition=models.Q(('quoted_price__gte', 0)), name='non_negative_quoted_price'),
        ),
    ]
