# Generated by Django 5.2.4 on 2025-08-07 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('leads', '0004_lead_leads_status_94f025_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads_created', to='authentication.serviceproviderprofile'),
        ),
    ]
