# Generated by Django 5.2.4 on 2025-08-07 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('leads', '0006_alter_lead_id'),
        ('packages', '0007_alter_package_provider'),
        ('services', '0005_alter_service_provider'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lead',
            name='positive_number_of_people',
        ),
        migrations.RemoveConstraint(
            model_name='lead',
            name='non_negative_priority',
        ),
        migrations.RemoveConstraint(
            model_name='leaddistribution',
            name='non_negative_quoted_price',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_user_id_57eab3_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_package_7f3c00_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_service_0d1945_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_preferr_43c140_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_is_dist_336b8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_created_e6e479_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_status_94f025_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_expires_9de04f_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaddistribution',
            name='lead_distri_lead_id_80d688_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaddistribution',
            name='lead_distri_provide_1419cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaddistribution',
            name='lead_distri_sent_at_bb39d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaddistribution',
            name='lead_distri_status_fc39a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='leadinteraction',
            name='lead_intera_lead_id_b9024a_idx',
        ),
        migrations.RemoveIndex(
            model_name='leadinteraction',
            name='lead_intera_interac_395f50_idx',
        ),
        migrations.RemoveIndex(
            model_name='leadinteraction',
            name='lead_intera_interac_40e2bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='leadinteraction',
            name='lead_intera_is_succ_835f6e_idx',
        ),
        migrations.RemoveIndex(
            model_name='leadnote',
            name='lead_notes_lead_id_421b7c_idx',
        ),
        migrations.RemoveIndex(
            model_name='leadnote',
            name='lead_notes_is_priv_885890_idx',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='custom_message',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='preferred_hotel_category',
        ),
        migrations.RemoveField(
            model_name='leaddistribution',
            name='app_notification_sent',
        ),
        migrations.RemoveField(
            model_name='leaddistribution',
            name='email_sent',
        ),
        migrations.RemoveField(
            model_name='leaddistribution',
            name='sms_sent',
        ),
        migrations.RemoveField(
            model_name='leadinteraction',
            name='follow_up_notes',
        ),
        migrations.AlterField(
            model_name='lead',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.package'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='selected_services',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='lead',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.serviceproviderprofile'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(default='web', max_length=50),
        ),
        migrations.AlterField(
            model_name='leaddistribution',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_distributions', to='authentication.serviceproviderprofile'),
        ),
        migrations.AlterField(
            model_name='leadinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('meeting', 'Meeting'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leadinteraction',
            name='notes',
            field=models.TextField(blank=True, default='No notes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leadinteraction',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='authentication.serviceproviderprofile'),
        ),
        migrations.AlterField(
            model_name='leadnote',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='authentication.serviceproviderprofile'),
        ),
    ]
