# Generated by Django 5.2.5 on 2025-12-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_upload_services',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='cross_business_leads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='dedicated_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='featured_in_all_categories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_services',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='unlimited_business_types',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='unlimited_uploads',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('ultra_premium', 'Ultra Premium')], max_length=20),
        ),
    ]
