# Generated by Django 5.2.5 on 2026-02-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionplan_credits_included_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credits', models.PositiveIntegerField(help_text='Number of credits in this pack')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in INR', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('icon_type', models.CharField(default='zap', help_text='Lucide icon name', max_length=50)),
                ('savings_text', models.CharField(blank=True, help_text='e.g. 20% OFF', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_months',
            field=models.IntegerField(choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (12, '12 Months'), (24, '24 Months'), (36, '36 Months')]),
        ),
    ]
