# Generated by Django 5.2.5 on 2026-10-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('renewal', 'Renewal'), ('upgrade', 'Upgrade'), ('addon', 'Add-on'), ('airport_attendant', 'Airport Attendant')], default='subscription', max_length=20),
        ),
    ]
