# Generated by Django 5.2.5 on 2026-01-22 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destination_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PopularDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('destination_type', models.CharField(choices=[('hajj', 'Hajj'), ('umrah', 'Umrah'), ('ziyarat', 'Ziyarat')], max_length=50)),
                ('ziyarat_type', models.CharField(blank=True, choices=[('masjid_al_haram', 'Masjid al-Haram'), ('masjid_an_nabawi', 'Masjid an-Nabawi'), ('jabal_rahma', 'Jabal Rahma'), ('jannah_al_baqi', 'Jannah al-Baqi'), ('jabal_thawr', 'Jabal Thawr'), ('hudaibiyah', 'Hudaibiyah'), ('other_sites', 'Other Islamic Sites')], max_length=50)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('detailed_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='destinations/')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Saudi Arabia', max_length=100)),
                ('historical_significance', models.TextField(blank=True)),
                ('prayers_recommended', models.TextField(blank=True)),
                ('rituals_associated', models.TextField(blank=True)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=200)),
                ('visiting_hours', models.CharField(blank=True, max_length=200)),
                ('dress_code', models.TextField(blank=True)),
                ('accessibility_info', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery_images', models.ManyToManyField(blank=True, to='banners.destinationimage')),
            ],
            options={
                'ordering': ['display_order', '-is_featured', '-view_count'],
            },
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='banners.populardestination'),
        ),
        migrations.CreateModel(
            name='VisitorTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_tips', to='banners.populardestination')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='banners/')),
                ('banner_type', models.CharField(choices=[('main_screen', 'Main Screen Banner'), ('offer', 'Offer Banner')], default='main_screen', max_length=50)),
                ('provider_business_type', models.CharField(blank=True, help_text='Show banner only to providers of specific business type', max_length=50)),
                ('target_city', models.CharField(blank=True, max_length=100)),
                ('target_state', models.CharField(blank=True, max_length=100)),
                ('target_country', models.CharField(blank=True, max_length=100)),
                ('display_priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', max_length=20)),
                ('priority_weight', models.IntegerField(default=1, help_text='Higher weight = higher priority (1-10)')),
                ('external_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('target_user_types', models.JSONField(blank=True, default=list, help_text="List of user types to target (e.g., ['pilgrim', 'provider'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'provider'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority_weight', 'display_order', '-created_at'],
                'indexes': [models.Index(fields=['banner_type', 'is_active', 'display_priority'], name='banners_ban_banner__ceda3c_idx'), models.Index(fields=['provider', 'is_active'], name='banners_ban_provide_026bd0_idx'), models.Index(fields=['target_city', 'target_state', 'is_active'], name='banners_ban_target__0b2e74_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='populardestination',
            index=models.Index(fields=['destination_type', 'is_active'], name='banners_pop_destina_fceb42_idx'),
        ),
        migrations.AddIndex(
            model_name='populardestination',
            index=models.Index(fields=['ziyarat_type', 'is_active'], name='banners_pop_ziyarat_d65cdd_idx'),
        ),
    ]
