# Generated by Django 5.2.5 on 2026-01-22 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='target_user_types',
        ),
    ]
