# Generated by Django 5.2.5 on 2026-10-05 10:21

import apps.airport_attendants.private_storage
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_alter_payment_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AirportAttendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pan_document', models.FileField(blank=True, storage=apps.airport_attendants.private_storage.PrivateKYCStorage(), upload_to='airport_attendants/pan/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('aadhaar_document', models.FileField(blank=True, storage=apps.airport_attendants.private_storage.PrivateKYCStorage(), upload_to='airport_attendants/aadhaar/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendants', to='airport_attendants.airport')),
            ],
            options={
                'ordering': ['airport__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AirportAttendantBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_time', models.TimeField()),
                ('flight_name', models.CharField(max_length=150)),
                ('flight_number', models.CharField(max_length=30)),
                ('pilgrim_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='awaiting_payment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='airport_attendants.airport')),
                ('attendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='airport_attendants.airportattendant')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='airport_attendant_bookings', to='payments.payment')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airport_attendant_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['airport', 'service_date', 'service_time', 'status'], name='airport_att_airport_bac839_idx'), models.Index(fields=['attendant', 'service_date', 'service_time', 'status'], name='airport_att_attenda_431a37_idx')],
            },
        ),
    ]
