# Generated by Django 5.2.5 on 2025-12-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='business_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('agency', 'Travel Agency'), ('visa', 'Visa'), ('hotels', 'Hotels'), ('transport', 'Transport'), ('food', 'Food'), ('laundry', 'Laundry'), ('air_ticket_group_fare_umrah', 'Air Ticket Group Fare Umrah'), ('umrah_guide', 'Umrah Guide'), ('umrah_kit', 'Umrah Kit'), ('jam_jam_water', 'Jam Jam Water'), ('full_package', 'Full Package')], max_length=50),
        ),
    ]
