# Generated by Django 5.2.5 on 2026-02-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_serviceproviderprofile_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='business_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='business_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='business_phone',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='business_pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='business_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='business_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('company', 'Company'), ('agency', 'Travel Agency'), ('visa', 'Visa'), ('hotels', 'Hotels'), ('transport', 'Transport'), ('food', 'Food'), ('laundry', 'Laundry'), ('air_ticket_group_fare_umrah', 'Air Ticket Group Fare Umrah'), ('umrah_guide', 'Umrah Guide'), ('umrah_kit', 'Umrah Kit'), ('jam_jam_water', 'Jam Jam Water'), ('full_package', 'Full Package')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='government_id_document',
            field=models.FileField(blank=True, null=True, upload_to='government_ids/'),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='government_id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='government_id_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
