# Generated by Django 5.2.5 on 2026-03-23 10:31

import apps.authentication.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_serviceproviderprofile_business_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logos/', validators=[apps.authentication.models.validate_file_size]),
        ),
        migrations.CreateModel(
            name='ProviderMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='provider_media/', validators=[apps.authentication.models.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='authentication.serviceproviderprofile')),
            ],
            options={
                'verbose_name': 'Provider Media',
                'verbose_name_plural': 'Provider Media',
                'db_table': 'provider_media',
                'ordering': ['-created_at'],
            },
        ),
    ]
