# Generated by Django 5.2.4 on 2025-07-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_usersession_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('pilgrim', 'Pilgrim'), ('provider', 'Service Provider'), ('super_admin', 'Super Admin')], default='pilgrim', max_length=20),
        ),
    ]
