# Generated by Django 5.2.5 on 2026-05-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_serviceproviderprofile_business_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('registration', 'Registration'), ('view_package', 'View Package'), ('inquiry_sent', 'Inquiry Sent'), ('package_saved', 'Package Saved'), ('package_unsaved', 'Package Unsaved'), ('search_performed', 'Search Performed'), ('profile_update', 'Profile Update'), ('profile_deactivation', 'Profile Deactivation'), ('location_update', 'Location Update'), ('password_change', 'Password Change'), ('password_reset_otp_verified', 'Password Reset OTP Verified'), ('password_reset_complete', 'Password Reset Complete'), ('email_verification', 'Email Verification'), ('phone_verification', 'Phone Verification'), ('account_deactivation', 'Account Deactivation'), ('account_reactivation', 'Account Reactivation'), ('account_deletion', 'Account Deletion'), ('data_export', 'Data Export'), ('bulk_action', 'Bulk Action'), ('settings_update', 'Settings Update'), ('preferences_update', 'Preferences Update'), ('app_open_location_update', 'App Open Location Update')], max_length=50),
        ),
    ]
