# Generated by Django 5.2.5 on 2026-09-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_activity_types_and_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='profile_views',
            field=models.IntegerField(default=0),
        ),
    ]
