# Generated by Django 5.2.5 on 2026-10-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
