# Generated by Django 5.2.5 on 2026-10-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_unused_provider_contact_views_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='target_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
