# Generated by Django 5.2.4 on 2025-08-22 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('lead_received', 'Lead Received'), ('subscription_expiry', 'Subscription Expiry'), ('package_approved', 'Package Approved'), ('package_rejected', 'Package Rejected'), ('new_review', 'New Review'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('subscription_reminder', 'Subscription Reminder'), ('package_upload_reminder', 'Package Upload Reminder'), ('verification_complete', 'Verification Complete'), ('welcome', 'Welcome'), ('password_reset', 'Password Reset')], default='lead_received', max_length=50)),
                ('target_user_type', models.CharField(choices=[('all', 'All Users'), ('pilgrim', 'Pilgrims'), ('provider', 'Service Providers')], default='all', max_length=20)),
                ('target_filters', models.JSONField(blank=True, default=dict)),
                ('send_email', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('send_app', models.BooleanField(default=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bulk_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('lead_received', 'Lead Received'), ('subscription_expiry', 'Subscription Expiry'), ('package_approved', 'Package Approved'), ('package_rejected', 'Package Rejected'), ('new_review', 'New Review'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('subscription_reminder', 'Subscription Reminder'), ('package_upload_reminder', 'Package Upload Reminder'), ('verification_complete', 'Verification Complete'), ('welcome', 'Welcome'), ('password_reset', 'Password Reset')], default='lead_received', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('send_email', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('send_app', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('app_sent', models.BooleanField(default=False)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('app', 'App')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification')),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_lead_notifications', models.BooleanField(default=True)),
                ('email_subscription_notifications', models.BooleanField(default=True)),
                ('email_package_notifications', models.BooleanField(default=True)),
                ('email_review_notifications', models.BooleanField(default=True)),
                ('email_pay_notifications', models.BooleanField(default=True)),
                ('email_verification_notifications', models.BooleanField(default=True)),
                ('email_marketing', models.BooleanField(default=False)),
                ('sms_lead_notifications', models.BooleanField(default=True)),
                ('sms_subscription_notifications', models.BooleanField(default=True)),
                ('sms_package_notifications', models.BooleanField(default=False)),
                ('sms_review_notifications', models.BooleanField(default=False)),
                ('sms_payment_notifications', models.BooleanField(default=True)),
                ('sms_verification_notifications', models.BooleanField(default=False)),
                ('sms_marketing', models.BooleanField(default=False)),
                ('app_lead_notifications', models.BooleanField(default=True)),
                ('app_subscription_notifications', models.BooleanField(default=True)),
                ('app_package_notifications', models.BooleanField(default=True)),
                ('app_review_notifications', models.BooleanField(default=True)),
                ('app_payment_notifications', models.BooleanField(default=True)),
                ('app_verification_notifications', models.BooleanField(default=True)),
                ('app_marketing', models.BooleanField(default=False)),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='immediate', max_length=20)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'status'], name='notificatio_recipie_218e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'status'], name='notificatio_notific_21f913_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'next_retry_at'], name='notificatio_status_d9cbdc_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification', 'channel'], name='notificatio_notific_6b2a25_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['sent_at'], name='notificatio_sent_at_85d1ed_idx'),
        ),
    ]
