# Generated by Django 5.2.4 on 2025-08-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_bulknotification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulknotification',
            name='notification_type',
            field=models.CharField(choices=[('lead_received', 'Lead Received'), ('subscription_expiry', 'Subscription Expiry'), ('package_approved', 'Package Approved'), ('package_rejected', 'Package Rejected'), ('services_approved', 'Service Approved'), ('services_rejected', 'Service Rejected'), ('new_review', 'New Review'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('subscription_reminder', 'Subscription Reminder'), ('package_upload_reminder', 'Package Upload Reminder'), ('verification_complete', 'Verification Complete'), ('welcome', 'Welcome'), ('password_reset', 'Password Reset')], default='lead_received', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lead_received', 'Lead Received'), ('subscription_expiry', 'Subscription Expiry'), ('package_approved', 'Package Approved'), ('package_rejected', 'Package Rejected'), ('services_approved', 'Service Approved'), ('services_rejected', 'Service Rejected'), ('new_review', 'New Review'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('subscription_reminder', 'Subscription Reminder'), ('package_upload_reminder', 'Package Upload Reminder'), ('verification_complete', 'Verification Complete'), ('welcome', 'Welcome'), ('password_reset', 'Password Reset')], default='lead_received', max_length=50),
        ),
    ]
